-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity product is
port (
    ap_ready : OUT STD_LOGIC;
    a_V : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V : IN STD_LOGIC_VECTOR (27 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of product is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal r_V_fu_34_p0 : STD_LOGIC_VECTOR (27 downto 0);
    signal r_V_fu_34_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_fu_34_p2 : STD_LOGIC_VECTOR (55 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= r_V_fu_34_p2(55 downto 24);
    r_V_fu_34_p0 <= w_V;
    r_V_fu_34_p1 <= a_V;
    r_V_fu_34_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(r_V_fu_34_p0) * signed(r_V_fu_34_p1))), 56));
end behav;
