// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fpga_ANN50x50,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xazu7eg-fbvb900-1-i,HLS_INPUT_CLOCK=24.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=19.540000,HLS_SYN_LAT=11,HLS_SYN_TPT=4,HLS_SYN_MEM=18,HLS_SYN_DSP=1150,HLS_SYN_FF=15386,HLS_SYN_LUT=154511,HLS_VERSION=2019_1}" *)

module fpga_ANN50x50 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_V,
        input_V_ap_vld,
        layer7_out_V,
        layer7_out_V_ap_vld,
        const_size_in_1,
        const_size_in_1_ap_vld,
        const_size_out_1,
        const_size_out_1_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [863:0] input_V;
input   input_V_ap_vld;
output  [143:0] layer7_out_V;
output   layer7_out_V_ap_vld;
output  [15:0] const_size_in_1;
output   const_size_in_1_ap_vld;
output  [15:0] const_size_out_1;
output   const_size_out_1_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer7_out_V_ap_vld;
reg const_size_in_1_ap_vld;
reg const_size_out_1_ap_vld;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state8_pp0_stage3_iter1;
wire    ap_block_state12_pp0_stage3_iter2;
wire    ap_block_pp0_stage3_11001;
reg   [863:0] input_V_preg;
reg   [863:0] input_V_in_sig;
reg    input_V_ap_vld_preg;
reg    input_V_ap_vld_in_sig;
reg    input_V_blk_n;
wire    ap_block_pp0_stage0;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state7_pp0_stage2_iter1;
wire    ap_block_state11_pp0_stage2_iter2;
wire    ap_block_pp0_stage2_11001;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage3_subdone;
wire    grp_dense_latency_0_0_0_1_fu_83_ap_start;
wire    grp_dense_latency_0_0_0_1_fu_83_ap_done;
wire    grp_dense_latency_0_0_0_1_fu_83_ap_idle;
wire    grp_dense_latency_0_0_0_1_fu_83_ap_ready;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_0;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_1;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_2;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_3;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_4;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_5;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_6;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_7;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_8;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_9;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_10;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_11;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_12;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_13;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_14;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_15;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_16;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_17;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_18;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_19;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_20;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_21;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_22;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_23;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_24;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_25;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_26;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_27;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_28;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_29;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_30;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_31;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_32;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_33;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_34;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_35;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_36;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_37;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_38;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_39;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_40;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_41;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_42;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_43;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_44;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_45;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_46;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_47;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_48;
wire   [23:0] grp_dense_latency_0_0_0_1_fu_83_ap_return_49;
reg    grp_dense_latency_0_0_0_1_fu_83_ap_ce;
wire    ap_block_state4_pp0_stage3_iter0_ignore_call113;
wire    ap_block_state8_pp0_stage3_iter1_ignore_call113;
wire    ap_block_state12_pp0_stage3_iter2_ignore_call113;
wire    ap_block_pp0_stage3_11001_ignoreCallOp119;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call113;
wire    ap_block_state5_pp0_stage0_iter1_ignore_call113;
wire    ap_block_state9_pp0_stage0_iter2_ignore_call113;
reg    ap_block_pp0_stage0_11001_ignoreCallOp120;
wire    ap_block_state2_pp0_stage1_iter0_ignore_call113;
wire    ap_block_state6_pp0_stage1_iter1_ignore_call113;
wire    ap_block_state10_pp0_stage1_iter2_ignore_call113;
wire    ap_block_pp0_stage1_11001_ignoreCallOp121;
wire    ap_block_state3_pp0_stage2_iter0_ignore_call113;
wire    ap_block_state7_pp0_stage2_iter1_ignore_call113;
wire    ap_block_state11_pp0_stage2_iter2_ignore_call113;
wire    ap_block_pp0_stage2_11001_ignoreCallOp122;
wire    ap_CS_fsm_pp0_stage1;
reg    grp_dense_latency_0_0_0_2_fu_137_ap_start;
wire    grp_dense_latency_0_0_0_2_fu_137_ap_done;
wire    grp_dense_latency_0_0_0_2_fu_137_ap_idle;
wire    grp_dense_latency_0_0_0_2_fu_137_ap_ready;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_0;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_1;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_2;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_3;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_4;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_5;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_6;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_7;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_8;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_9;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_10;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_11;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_12;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_13;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_14;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_15;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_16;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_17;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_18;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_19;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_20;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_21;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_22;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_23;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_24;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_25;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_26;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_27;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_28;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_29;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_30;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_31;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_32;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_33;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_34;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_35;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_36;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_37;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_38;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_39;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_40;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_41;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_42;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_43;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_44;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_45;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_46;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_47;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_48;
wire   [23:0] grp_dense_latency_0_0_0_2_fu_137_ap_return_49;
reg    grp_dense_latency_0_0_0_2_fu_137_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call11;
wire    ap_block_state5_pp0_stage0_iter1_ignore_call11;
wire    ap_block_state9_pp0_stage0_iter2_ignore_call11;
reg    ap_block_pp0_stage0_11001_ignoreCallOp14;
wire    ap_block_state2_pp0_stage1_iter0_ignore_call11;
wire    ap_block_state6_pp0_stage1_iter1_ignore_call11;
wire    ap_block_state10_pp0_stage1_iter2_ignore_call11;
wire    ap_block_pp0_stage1_11001_ignoreCallOp15;
wire    ap_block_state3_pp0_stage2_iter0_ignore_call11;
wire    ap_block_state7_pp0_stage2_iter1_ignore_call11;
wire    ap_block_state11_pp0_stage2_iter2_ignore_call11;
wire    ap_block_pp0_stage2_11001_ignoreCallOp16;
wire    ap_block_state4_pp0_stage3_iter0_ignore_call11;
wire    ap_block_state8_pp0_stage3_iter1_ignore_call11;
wire    ap_block_state12_pp0_stage3_iter2_ignore_call11;
wire    ap_block_pp0_stage3_11001_ignoreCallOp17;
wire    grp_dense_latency_0_0_0_s_fu_143_ap_start;
wire    grp_dense_latency_0_0_0_s_fu_143_ap_done;
wire    grp_dense_latency_0_0_0_s_fu_143_ap_idle;
wire    grp_dense_latency_0_0_0_s_fu_143_ap_ready;
wire   [23:0] grp_dense_latency_0_0_0_s_fu_143_ap_return_0;
wire   [23:0] grp_dense_latency_0_0_0_s_fu_143_ap_return_1;
wire   [23:0] grp_dense_latency_0_0_0_s_fu_143_ap_return_2;
wire   [23:0] grp_dense_latency_0_0_0_s_fu_143_ap_return_3;
wire   [23:0] grp_dense_latency_0_0_0_s_fu_143_ap_return_4;
wire   [23:0] grp_dense_latency_0_0_0_s_fu_143_ap_return_5;
reg    grp_dense_latency_0_0_0_s_fu_143_ap_ce;
wire    ap_block_state3_pp0_stage2_iter0_ignore_call215;
wire    ap_block_state7_pp0_stage2_iter1_ignore_call215;
wire    ap_block_state11_pp0_stage2_iter2_ignore_call215;
wire    ap_block_pp0_stage2_11001_ignoreCallOp224;
wire    ap_block_state4_pp0_stage3_iter0_ignore_call215;
wire    ap_block_state8_pp0_stage3_iter1_ignore_call215;
wire    ap_block_state12_pp0_stage3_iter2_ignore_call215;
wire    ap_block_pp0_stage3_11001_ignoreCallOp225;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call215;
wire    ap_block_state5_pp0_stage0_iter1_ignore_call215;
wire    ap_block_state9_pp0_stage0_iter2_ignore_call215;
reg    ap_block_pp0_stage0_11001_ignoreCallOp226;
wire    ap_block_state2_pp0_stage1_iter0_ignore_call215;
wire    ap_block_state6_pp0_stage1_iter1_ignore_call215;
wire    ap_block_state10_pp0_stage1_iter2_ignore_call215;
wire    ap_block_pp0_stage1_11001_ignoreCallOp227;
wire    grp_softmax_fu_197_ap_start;
wire    grp_softmax_fu_197_ap_done;
wire    grp_softmax_fu_197_ap_idle;
wire    grp_softmax_fu_197_ap_ready;
reg    grp_softmax_fu_197_ap_ce;
wire   [140:0] grp_softmax_fu_197_ap_return;
wire    ap_block_state2_pp0_stage1_iter0_ignore_call222;
wire    ap_block_state6_pp0_stage1_iter1_ignore_call222;
wire    ap_block_state10_pp0_stage1_iter2_ignore_call222;
wire    ap_block_pp0_stage1_11001_ignoreCallOp234;
wire    ap_block_state3_pp0_stage2_iter0_ignore_call222;
wire    ap_block_state7_pp0_stage2_iter1_ignore_call222;
wire    ap_block_state11_pp0_stage2_iter2_ignore_call222;
wire    ap_block_pp0_stage2_11001_ignoreCallOp235;
wire    ap_block_state4_pp0_stage3_iter0_ignore_call222;
wire    ap_block_state8_pp0_stage3_iter1_ignore_call222;
wire    ap_block_state12_pp0_stage3_iter2_ignore_call222;
wire    ap_block_pp0_stage3_11001_ignoreCallOp246;
wire    call_ret1_relu_1_fu_211_ap_ready;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_0;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_1;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_2;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_3;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_4;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_5;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_6;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_7;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_8;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_9;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_10;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_11;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_12;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_13;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_14;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_15;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_16;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_17;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_18;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_19;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_20;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_21;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_22;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_23;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_24;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_25;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_26;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_27;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_28;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_29;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_30;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_31;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_32;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_33;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_34;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_35;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_36;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_37;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_38;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_39;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_40;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_41;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_42;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_43;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_44;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_45;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_46;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_47;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_48;
wire   [23:0] call_ret1_relu_1_fu_211_ap_return_49;
wire    call_ret3_relu_fu_265_ap_ready;
wire   [23:0] call_ret3_relu_fu_265_ap_return_0;
wire   [23:0] call_ret3_relu_fu_265_ap_return_1;
wire   [23:0] call_ret3_relu_fu_265_ap_return_2;
wire   [23:0] call_ret3_relu_fu_265_ap_return_3;
wire   [23:0] call_ret3_relu_fu_265_ap_return_4;
wire   [23:0] call_ret3_relu_fu_265_ap_return_5;
wire   [23:0] call_ret3_relu_fu_265_ap_return_6;
wire   [23:0] call_ret3_relu_fu_265_ap_return_7;
wire   [23:0] call_ret3_relu_fu_265_ap_return_8;
wire   [23:0] call_ret3_relu_fu_265_ap_return_9;
wire   [23:0] call_ret3_relu_fu_265_ap_return_10;
wire   [23:0] call_ret3_relu_fu_265_ap_return_11;
wire   [23:0] call_ret3_relu_fu_265_ap_return_12;
wire   [23:0] call_ret3_relu_fu_265_ap_return_13;
wire   [23:0] call_ret3_relu_fu_265_ap_return_14;
wire   [23:0] call_ret3_relu_fu_265_ap_return_15;
wire   [23:0] call_ret3_relu_fu_265_ap_return_16;
wire   [23:0] call_ret3_relu_fu_265_ap_return_17;
wire   [23:0] call_ret3_relu_fu_265_ap_return_18;
wire   [23:0] call_ret3_relu_fu_265_ap_return_19;
wire   [23:0] call_ret3_relu_fu_265_ap_return_20;
wire   [23:0] call_ret3_relu_fu_265_ap_return_21;
wire   [23:0] call_ret3_relu_fu_265_ap_return_22;
wire   [23:0] call_ret3_relu_fu_265_ap_return_23;
wire   [23:0] call_ret3_relu_fu_265_ap_return_24;
wire   [23:0] call_ret3_relu_fu_265_ap_return_25;
wire   [23:0] call_ret3_relu_fu_265_ap_return_26;
wire   [23:0] call_ret3_relu_fu_265_ap_return_27;
wire   [23:0] call_ret3_relu_fu_265_ap_return_28;
wire   [23:0] call_ret3_relu_fu_265_ap_return_29;
wire   [23:0] call_ret3_relu_fu_265_ap_return_30;
wire   [23:0] call_ret3_relu_fu_265_ap_return_31;
wire   [23:0] call_ret3_relu_fu_265_ap_return_32;
wire   [23:0] call_ret3_relu_fu_265_ap_return_33;
wire   [23:0] call_ret3_relu_fu_265_ap_return_34;
wire   [23:0] call_ret3_relu_fu_265_ap_return_35;
wire   [23:0] call_ret3_relu_fu_265_ap_return_36;
wire   [23:0] call_ret3_relu_fu_265_ap_return_37;
wire   [23:0] call_ret3_relu_fu_265_ap_return_38;
wire   [23:0] call_ret3_relu_fu_265_ap_return_39;
wire   [23:0] call_ret3_relu_fu_265_ap_return_40;
wire   [23:0] call_ret3_relu_fu_265_ap_return_41;
wire   [23:0] call_ret3_relu_fu_265_ap_return_42;
wire   [23:0] call_ret3_relu_fu_265_ap_return_43;
wire   [23:0] call_ret3_relu_fu_265_ap_return_44;
wire   [23:0] call_ret3_relu_fu_265_ap_return_45;
wire   [23:0] call_ret3_relu_fu_265_ap_return_46;
wire   [23:0] call_ret3_relu_fu_265_ap_return_47;
wire   [23:0] call_ret3_relu_fu_265_ap_return_48;
wire   [23:0] call_ret3_relu_fu_265_ap_return_49;
reg    grp_dense_latency_0_0_0_1_fu_83_ap_start_reg;
wire    ap_block_pp0_stage3;
reg    grp_dense_latency_0_0_0_s_fu_143_ap_start_reg;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state6_pp0_stage1_iter1;
wire    ap_block_state10_pp0_stage1_iter2;
wire    ap_block_pp0_stage1_11001;
wire    ap_block_pp0_stage2;
reg    grp_softmax_fu_197_ap_start_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
wire    ap_block_state9_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage3_01001;
reg   [3:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to2;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 input_V_preg = 864'd0;
#0 input_V_ap_vld_preg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 grp_dense_latency_0_0_0_1_fu_83_ap_start_reg = 1'b0;
#0 grp_dense_latency_0_0_0_s_fu_143_ap_start_reg = 1'b0;
#0 grp_softmax_fu_197_ap_start_reg = 1'b0;
end

dense_latency_0_0_0_1 grp_dense_latency_0_0_0_1_fu_83(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_latency_0_0_0_1_fu_83_ap_start),
    .ap_done(grp_dense_latency_0_0_0_1_fu_83_ap_done),
    .ap_idle(grp_dense_latency_0_0_0_1_fu_83_ap_idle),
    .ap_ready(grp_dense_latency_0_0_0_1_fu_83_ap_ready),
    .data_0_V_read(call_ret1_relu_1_fu_211_ap_return_0),
    .data_1_V_read(call_ret1_relu_1_fu_211_ap_return_1),
    .data_2_V_read(call_ret1_relu_1_fu_211_ap_return_2),
    .data_3_V_read(call_ret1_relu_1_fu_211_ap_return_3),
    .data_4_V_read(call_ret1_relu_1_fu_211_ap_return_4),
    .data_5_V_read(call_ret1_relu_1_fu_211_ap_return_5),
    .data_6_V_read(call_ret1_relu_1_fu_211_ap_return_6),
    .data_7_V_read(call_ret1_relu_1_fu_211_ap_return_7),
    .data_8_V_read(call_ret1_relu_1_fu_211_ap_return_8),
    .data_9_V_read(call_ret1_relu_1_fu_211_ap_return_9),
    .data_10_V_read(call_ret1_relu_1_fu_211_ap_return_10),
    .data_11_V_read(call_ret1_relu_1_fu_211_ap_return_11),
    .data_12_V_read(call_ret1_relu_1_fu_211_ap_return_12),
    .data_13_V_read(call_ret1_relu_1_fu_211_ap_return_13),
    .data_14_V_read(call_ret1_relu_1_fu_211_ap_return_14),
    .data_15_V_read(call_ret1_relu_1_fu_211_ap_return_15),
    .data_16_V_read(call_ret1_relu_1_fu_211_ap_return_16),
    .data_17_V_read(call_ret1_relu_1_fu_211_ap_return_17),
    .data_18_V_read(call_ret1_relu_1_fu_211_ap_return_18),
    .data_19_V_read(call_ret1_relu_1_fu_211_ap_return_19),
    .data_20_V_read(call_ret1_relu_1_fu_211_ap_return_20),
    .data_21_V_read(call_ret1_relu_1_fu_211_ap_return_21),
    .data_22_V_read(call_ret1_relu_1_fu_211_ap_return_22),
    .data_23_V_read(call_ret1_relu_1_fu_211_ap_return_23),
    .data_24_V_read(call_ret1_relu_1_fu_211_ap_return_24),
    .data_25_V_read(call_ret1_relu_1_fu_211_ap_return_25),
    .data_26_V_read(call_ret1_relu_1_fu_211_ap_return_26),
    .data_27_V_read(call_ret1_relu_1_fu_211_ap_return_27),
    .data_28_V_read(call_ret1_relu_1_fu_211_ap_return_28),
    .data_29_V_read(call_ret1_relu_1_fu_211_ap_return_29),
    .data_30_V_read(call_ret1_relu_1_fu_211_ap_return_30),
    .data_31_V_read(call_ret1_relu_1_fu_211_ap_return_31),
    .data_32_V_read(call_ret1_relu_1_fu_211_ap_return_32),
    .data_33_V_read(call_ret1_relu_1_fu_211_ap_return_33),
    .data_34_V_read(call_ret1_relu_1_fu_211_ap_return_34),
    .data_35_V_read(call_ret1_relu_1_fu_211_ap_return_35),
    .data_36_V_read(call_ret1_relu_1_fu_211_ap_return_36),
    .data_37_V_read(call_ret1_relu_1_fu_211_ap_return_37),
    .data_38_V_read(call_ret1_relu_1_fu_211_ap_return_38),
    .data_39_V_read(call_ret1_relu_1_fu_211_ap_return_39),
    .data_40_V_read(call_ret1_relu_1_fu_211_ap_return_40),
    .data_41_V_read(call_ret1_relu_1_fu_211_ap_return_41),
    .data_42_V_read(call_ret1_relu_1_fu_211_ap_return_42),
    .data_43_V_read(call_ret1_relu_1_fu_211_ap_return_43),
    .data_44_V_read(call_ret1_relu_1_fu_211_ap_return_44),
    .data_45_V_read(call_ret1_relu_1_fu_211_ap_return_45),
    .data_46_V_read(call_ret1_relu_1_fu_211_ap_return_46),
    .data_47_V_read(call_ret1_relu_1_fu_211_ap_return_47),
    .data_48_V_read(call_ret1_relu_1_fu_211_ap_return_48),
    .data_49_V_read(call_ret1_relu_1_fu_211_ap_return_49),
    .ap_return_0(grp_dense_latency_0_0_0_1_fu_83_ap_return_0),
    .ap_return_1(grp_dense_latency_0_0_0_1_fu_83_ap_return_1),
    .ap_return_2(grp_dense_latency_0_0_0_1_fu_83_ap_return_2),
    .ap_return_3(grp_dense_latency_0_0_0_1_fu_83_ap_return_3),
    .ap_return_4(grp_dense_latency_0_0_0_1_fu_83_ap_return_4),
    .ap_return_5(grp_dense_latency_0_0_0_1_fu_83_ap_return_5),
    .ap_return_6(grp_dense_latency_0_0_0_1_fu_83_ap_return_6),
    .ap_return_7(grp_dense_latency_0_0_0_1_fu_83_ap_return_7),
    .ap_return_8(grp_dense_latency_0_0_0_1_fu_83_ap_return_8),
    .ap_return_9(grp_dense_latency_0_0_0_1_fu_83_ap_return_9),
    .ap_return_10(grp_dense_latency_0_0_0_1_fu_83_ap_return_10),
    .ap_return_11(grp_dense_latency_0_0_0_1_fu_83_ap_return_11),
    .ap_return_12(grp_dense_latency_0_0_0_1_fu_83_ap_return_12),
    .ap_return_13(grp_dense_latency_0_0_0_1_fu_83_ap_return_13),
    .ap_return_14(grp_dense_latency_0_0_0_1_fu_83_ap_return_14),
    .ap_return_15(grp_dense_latency_0_0_0_1_fu_83_ap_return_15),
    .ap_return_16(grp_dense_latency_0_0_0_1_fu_83_ap_return_16),
    .ap_return_17(grp_dense_latency_0_0_0_1_fu_83_ap_return_17),
    .ap_return_18(grp_dense_latency_0_0_0_1_fu_83_ap_return_18),
    .ap_return_19(grp_dense_latency_0_0_0_1_fu_83_ap_return_19),
    .ap_return_20(grp_dense_latency_0_0_0_1_fu_83_ap_return_20),
    .ap_return_21(grp_dense_latency_0_0_0_1_fu_83_ap_return_21),
    .ap_return_22(grp_dense_latency_0_0_0_1_fu_83_ap_return_22),
    .ap_return_23(grp_dense_latency_0_0_0_1_fu_83_ap_return_23),
    .ap_return_24(grp_dense_latency_0_0_0_1_fu_83_ap_return_24),
    .ap_return_25(grp_dense_latency_0_0_0_1_fu_83_ap_return_25),
    .ap_return_26(grp_dense_latency_0_0_0_1_fu_83_ap_return_26),
    .ap_return_27(grp_dense_latency_0_0_0_1_fu_83_ap_return_27),
    .ap_return_28(grp_dense_latency_0_0_0_1_fu_83_ap_return_28),
    .ap_return_29(grp_dense_latency_0_0_0_1_fu_83_ap_return_29),
    .ap_return_30(grp_dense_latency_0_0_0_1_fu_83_ap_return_30),
    .ap_return_31(grp_dense_latency_0_0_0_1_fu_83_ap_return_31),
    .ap_return_32(grp_dense_latency_0_0_0_1_fu_83_ap_return_32),
    .ap_return_33(grp_dense_latency_0_0_0_1_fu_83_ap_return_33),
    .ap_return_34(grp_dense_latency_0_0_0_1_fu_83_ap_return_34),
    .ap_return_35(grp_dense_latency_0_0_0_1_fu_83_ap_return_35),
    .ap_return_36(grp_dense_latency_0_0_0_1_fu_83_ap_return_36),
    .ap_return_37(grp_dense_latency_0_0_0_1_fu_83_ap_return_37),
    .ap_return_38(grp_dense_latency_0_0_0_1_fu_83_ap_return_38),
    .ap_return_39(grp_dense_latency_0_0_0_1_fu_83_ap_return_39),
    .ap_return_40(grp_dense_latency_0_0_0_1_fu_83_ap_return_40),
    .ap_return_41(grp_dense_latency_0_0_0_1_fu_83_ap_return_41),
    .ap_return_42(grp_dense_latency_0_0_0_1_fu_83_ap_return_42),
    .ap_return_43(grp_dense_latency_0_0_0_1_fu_83_ap_return_43),
    .ap_return_44(grp_dense_latency_0_0_0_1_fu_83_ap_return_44),
    .ap_return_45(grp_dense_latency_0_0_0_1_fu_83_ap_return_45),
    .ap_return_46(grp_dense_latency_0_0_0_1_fu_83_ap_return_46),
    .ap_return_47(grp_dense_latency_0_0_0_1_fu_83_ap_return_47),
    .ap_return_48(grp_dense_latency_0_0_0_1_fu_83_ap_return_48),
    .ap_return_49(grp_dense_latency_0_0_0_1_fu_83_ap_return_49),
    .ap_ce(grp_dense_latency_0_0_0_1_fu_83_ap_ce)
);

dense_latency_0_0_0_2 grp_dense_latency_0_0_0_2_fu_137(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_latency_0_0_0_2_fu_137_ap_start),
    .ap_done(grp_dense_latency_0_0_0_2_fu_137_ap_done),
    .ap_idle(grp_dense_latency_0_0_0_2_fu_137_ap_idle),
    .ap_ready(grp_dense_latency_0_0_0_2_fu_137_ap_ready),
    .data_V_read(input_V_in_sig),
    .ap_return_0(grp_dense_latency_0_0_0_2_fu_137_ap_return_0),
    .ap_return_1(grp_dense_latency_0_0_0_2_fu_137_ap_return_1),
    .ap_return_2(grp_dense_latency_0_0_0_2_fu_137_ap_return_2),
    .ap_return_3(grp_dense_latency_0_0_0_2_fu_137_ap_return_3),
    .ap_return_4(grp_dense_latency_0_0_0_2_fu_137_ap_return_4),
    .ap_return_5(grp_dense_latency_0_0_0_2_fu_137_ap_return_5),
    .ap_return_6(grp_dense_latency_0_0_0_2_fu_137_ap_return_6),
    .ap_return_7(grp_dense_latency_0_0_0_2_fu_137_ap_return_7),
    .ap_return_8(grp_dense_latency_0_0_0_2_fu_137_ap_return_8),
    .ap_return_9(grp_dense_latency_0_0_0_2_fu_137_ap_return_9),
    .ap_return_10(grp_dense_latency_0_0_0_2_fu_137_ap_return_10),
    .ap_return_11(grp_dense_latency_0_0_0_2_fu_137_ap_return_11),
    .ap_return_12(grp_dense_latency_0_0_0_2_fu_137_ap_return_12),
    .ap_return_13(grp_dense_latency_0_0_0_2_fu_137_ap_return_13),
    .ap_return_14(grp_dense_latency_0_0_0_2_fu_137_ap_return_14),
    .ap_return_15(grp_dense_latency_0_0_0_2_fu_137_ap_return_15),
    .ap_return_16(grp_dense_latency_0_0_0_2_fu_137_ap_return_16),
    .ap_return_17(grp_dense_latency_0_0_0_2_fu_137_ap_return_17),
    .ap_return_18(grp_dense_latency_0_0_0_2_fu_137_ap_return_18),
    .ap_return_19(grp_dense_latency_0_0_0_2_fu_137_ap_return_19),
    .ap_return_20(grp_dense_latency_0_0_0_2_fu_137_ap_return_20),
    .ap_return_21(grp_dense_latency_0_0_0_2_fu_137_ap_return_21),
    .ap_return_22(grp_dense_latency_0_0_0_2_fu_137_ap_return_22),
    .ap_return_23(grp_dense_latency_0_0_0_2_fu_137_ap_return_23),
    .ap_return_24(grp_dense_latency_0_0_0_2_fu_137_ap_return_24),
    .ap_return_25(grp_dense_latency_0_0_0_2_fu_137_ap_return_25),
    .ap_return_26(grp_dense_latency_0_0_0_2_fu_137_ap_return_26),
    .ap_return_27(grp_dense_latency_0_0_0_2_fu_137_ap_return_27),
    .ap_return_28(grp_dense_latency_0_0_0_2_fu_137_ap_return_28),
    .ap_return_29(grp_dense_latency_0_0_0_2_fu_137_ap_return_29),
    .ap_return_30(grp_dense_latency_0_0_0_2_fu_137_ap_return_30),
    .ap_return_31(grp_dense_latency_0_0_0_2_fu_137_ap_return_31),
    .ap_return_32(grp_dense_latency_0_0_0_2_fu_137_ap_return_32),
    .ap_return_33(grp_dense_latency_0_0_0_2_fu_137_ap_return_33),
    .ap_return_34(grp_dense_latency_0_0_0_2_fu_137_ap_return_34),
    .ap_return_35(grp_dense_latency_0_0_0_2_fu_137_ap_return_35),
    .ap_return_36(grp_dense_latency_0_0_0_2_fu_137_ap_return_36),
    .ap_return_37(grp_dense_latency_0_0_0_2_fu_137_ap_return_37),
    .ap_return_38(grp_dense_latency_0_0_0_2_fu_137_ap_return_38),
    .ap_return_39(grp_dense_latency_0_0_0_2_fu_137_ap_return_39),
    .ap_return_40(grp_dense_latency_0_0_0_2_fu_137_ap_return_40),
    .ap_return_41(grp_dense_latency_0_0_0_2_fu_137_ap_return_41),
    .ap_return_42(grp_dense_latency_0_0_0_2_fu_137_ap_return_42),
    .ap_return_43(grp_dense_latency_0_0_0_2_fu_137_ap_return_43),
    .ap_return_44(grp_dense_latency_0_0_0_2_fu_137_ap_return_44),
    .ap_return_45(grp_dense_latency_0_0_0_2_fu_137_ap_return_45),
    .ap_return_46(grp_dense_latency_0_0_0_2_fu_137_ap_return_46),
    .ap_return_47(grp_dense_latency_0_0_0_2_fu_137_ap_return_47),
    .ap_return_48(grp_dense_latency_0_0_0_2_fu_137_ap_return_48),
    .ap_return_49(grp_dense_latency_0_0_0_2_fu_137_ap_return_49),
    .ap_ce(grp_dense_latency_0_0_0_2_fu_137_ap_ce)
);

dense_latency_0_0_0_s grp_dense_latency_0_0_0_s_fu_143(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_latency_0_0_0_s_fu_143_ap_start),
    .ap_done(grp_dense_latency_0_0_0_s_fu_143_ap_done),
    .ap_idle(grp_dense_latency_0_0_0_s_fu_143_ap_idle),
    .ap_ready(grp_dense_latency_0_0_0_s_fu_143_ap_ready),
    .data_0_V_read(call_ret3_relu_fu_265_ap_return_0),
    .data_1_V_read(call_ret3_relu_fu_265_ap_return_1),
    .data_2_V_read(call_ret3_relu_fu_265_ap_return_2),
    .data_3_V_read(call_ret3_relu_fu_265_ap_return_3),
    .data_4_V_read(call_ret3_relu_fu_265_ap_return_4),
    .data_5_V_read(call_ret3_relu_fu_265_ap_return_5),
    .data_6_V_read(call_ret3_relu_fu_265_ap_return_6),
    .data_7_V_read(call_ret3_relu_fu_265_ap_return_7),
    .data_8_V_read(call_ret3_relu_fu_265_ap_return_8),
    .data_9_V_read(call_ret3_relu_fu_265_ap_return_9),
    .data_10_V_read(call_ret3_relu_fu_265_ap_return_10),
    .data_11_V_read(call_ret3_relu_fu_265_ap_return_11),
    .data_12_V_read(call_ret3_relu_fu_265_ap_return_12),
    .data_13_V_read(call_ret3_relu_fu_265_ap_return_13),
    .data_14_V_read(call_ret3_relu_fu_265_ap_return_14),
    .data_15_V_read(call_ret3_relu_fu_265_ap_return_15),
    .data_16_V_read(call_ret3_relu_fu_265_ap_return_16),
    .data_17_V_read(call_ret3_relu_fu_265_ap_return_17),
    .data_18_V_read(call_ret3_relu_fu_265_ap_return_18),
    .data_19_V_read(call_ret3_relu_fu_265_ap_return_19),
    .data_20_V_read(call_ret3_relu_fu_265_ap_return_20),
    .data_21_V_read(call_ret3_relu_fu_265_ap_return_21),
    .data_22_V_read(call_ret3_relu_fu_265_ap_return_22),
    .data_23_V_read(call_ret3_relu_fu_265_ap_return_23),
    .data_24_V_read(call_ret3_relu_fu_265_ap_return_24),
    .data_25_V_read(call_ret3_relu_fu_265_ap_return_25),
    .data_26_V_read(call_ret3_relu_fu_265_ap_return_26),
    .data_27_V_read(call_ret3_relu_fu_265_ap_return_27),
    .data_28_V_read(call_ret3_relu_fu_265_ap_return_28),
    .data_29_V_read(call_ret3_relu_fu_265_ap_return_29),
    .data_30_V_read(call_ret3_relu_fu_265_ap_return_30),
    .data_31_V_read(call_ret3_relu_fu_265_ap_return_31),
    .data_32_V_read(call_ret3_relu_fu_265_ap_return_32),
    .data_33_V_read(call_ret3_relu_fu_265_ap_return_33),
    .data_34_V_read(call_ret3_relu_fu_265_ap_return_34),
    .data_35_V_read(call_ret3_relu_fu_265_ap_return_35),
    .data_36_V_read(call_ret3_relu_fu_265_ap_return_36),
    .data_37_V_read(call_ret3_relu_fu_265_ap_return_37),
    .data_38_V_read(call_ret3_relu_fu_265_ap_return_38),
    .data_39_V_read(call_ret3_relu_fu_265_ap_return_39),
    .data_40_V_read(call_ret3_relu_fu_265_ap_return_40),
    .data_41_V_read(call_ret3_relu_fu_265_ap_return_41),
    .data_42_V_read(call_ret3_relu_fu_265_ap_return_42),
    .data_43_V_read(call_ret3_relu_fu_265_ap_return_43),
    .data_44_V_read(call_ret3_relu_fu_265_ap_return_44),
    .data_45_V_read(call_ret3_relu_fu_265_ap_return_45),
    .data_46_V_read(call_ret3_relu_fu_265_ap_return_46),
    .data_47_V_read(call_ret3_relu_fu_265_ap_return_47),
    .data_48_V_read(call_ret3_relu_fu_265_ap_return_48),
    .data_49_V_read(call_ret3_relu_fu_265_ap_return_49),
    .ap_return_0(grp_dense_latency_0_0_0_s_fu_143_ap_return_0),
    .ap_return_1(grp_dense_latency_0_0_0_s_fu_143_ap_return_1),
    .ap_return_2(grp_dense_latency_0_0_0_s_fu_143_ap_return_2),
    .ap_return_3(grp_dense_latency_0_0_0_s_fu_143_ap_return_3),
    .ap_return_4(grp_dense_latency_0_0_0_s_fu_143_ap_return_4),
    .ap_return_5(grp_dense_latency_0_0_0_s_fu_143_ap_return_5),
    .ap_ce(grp_dense_latency_0_0_0_s_fu_143_ap_ce)
);

softmax grp_softmax_fu_197(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_softmax_fu_197_ap_start),
    .ap_done(grp_softmax_fu_197_ap_done),
    .ap_idle(grp_softmax_fu_197_ap_idle),
    .ap_ready(grp_softmax_fu_197_ap_ready),
    .ap_ce(grp_softmax_fu_197_ap_ce),
    .data_0_V_read(grp_dense_latency_0_0_0_s_fu_143_ap_return_0),
    .data_1_V_read(grp_dense_latency_0_0_0_s_fu_143_ap_return_1),
    .data_2_V_read(grp_dense_latency_0_0_0_s_fu_143_ap_return_2),
    .data_3_V_read(grp_dense_latency_0_0_0_s_fu_143_ap_return_3),
    .data_4_V_read(grp_dense_latency_0_0_0_s_fu_143_ap_return_4),
    .data_5_V_read(grp_dense_latency_0_0_0_s_fu_143_ap_return_5),
    .ap_return(grp_softmax_fu_197_ap_return)
);

relu_1 call_ret1_relu_1_fu_211(
    .ap_ready(call_ret1_relu_1_fu_211_ap_ready),
    .data_0_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_0),
    .data_1_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_1),
    .data_2_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_2),
    .data_3_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_3),
    .data_4_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_4),
    .data_5_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_5),
    .data_6_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_6),
    .data_7_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_7),
    .data_8_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_8),
    .data_9_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_9),
    .data_10_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_10),
    .data_11_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_11),
    .data_12_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_12),
    .data_13_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_13),
    .data_14_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_14),
    .data_15_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_15),
    .data_16_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_16),
    .data_17_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_17),
    .data_18_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_18),
    .data_19_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_19),
    .data_20_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_20),
    .data_21_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_21),
    .data_22_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_22),
    .data_23_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_23),
    .data_24_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_24),
    .data_25_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_25),
    .data_26_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_26),
    .data_27_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_27),
    .data_28_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_28),
    .data_29_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_29),
    .data_30_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_30),
    .data_31_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_31),
    .data_32_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_32),
    .data_33_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_33),
    .data_34_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_34),
    .data_35_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_35),
    .data_36_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_36),
    .data_37_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_37),
    .data_38_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_38),
    .data_39_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_39),
    .data_40_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_40),
    .data_41_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_41),
    .data_42_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_42),
    .data_43_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_43),
    .data_44_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_44),
    .data_45_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_45),
    .data_46_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_46),
    .data_47_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_47),
    .data_48_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_48),
    .data_49_V_read(grp_dense_latency_0_0_0_2_fu_137_ap_return_49),
    .ap_return_0(call_ret1_relu_1_fu_211_ap_return_0),
    .ap_return_1(call_ret1_relu_1_fu_211_ap_return_1),
    .ap_return_2(call_ret1_relu_1_fu_211_ap_return_2),
    .ap_return_3(call_ret1_relu_1_fu_211_ap_return_3),
    .ap_return_4(call_ret1_relu_1_fu_211_ap_return_4),
    .ap_return_5(call_ret1_relu_1_fu_211_ap_return_5),
    .ap_return_6(call_ret1_relu_1_fu_211_ap_return_6),
    .ap_return_7(call_ret1_relu_1_fu_211_ap_return_7),
    .ap_return_8(call_ret1_relu_1_fu_211_ap_return_8),
    .ap_return_9(call_ret1_relu_1_fu_211_ap_return_9),
    .ap_return_10(call_ret1_relu_1_fu_211_ap_return_10),
    .ap_return_11(call_ret1_relu_1_fu_211_ap_return_11),
    .ap_return_12(call_ret1_relu_1_fu_211_ap_return_12),
    .ap_return_13(call_ret1_relu_1_fu_211_ap_return_13),
    .ap_return_14(call_ret1_relu_1_fu_211_ap_return_14),
    .ap_return_15(call_ret1_relu_1_fu_211_ap_return_15),
    .ap_return_16(call_ret1_relu_1_fu_211_ap_return_16),
    .ap_return_17(call_ret1_relu_1_fu_211_ap_return_17),
    .ap_return_18(call_ret1_relu_1_fu_211_ap_return_18),
    .ap_return_19(call_ret1_relu_1_fu_211_ap_return_19),
    .ap_return_20(call_ret1_relu_1_fu_211_ap_return_20),
    .ap_return_21(call_ret1_relu_1_fu_211_ap_return_21),
    .ap_return_22(call_ret1_relu_1_fu_211_ap_return_22),
    .ap_return_23(call_ret1_relu_1_fu_211_ap_return_23),
    .ap_return_24(call_ret1_relu_1_fu_211_ap_return_24),
    .ap_return_25(call_ret1_relu_1_fu_211_ap_return_25),
    .ap_return_26(call_ret1_relu_1_fu_211_ap_return_26),
    .ap_return_27(call_ret1_relu_1_fu_211_ap_return_27),
    .ap_return_28(call_ret1_relu_1_fu_211_ap_return_28),
    .ap_return_29(call_ret1_relu_1_fu_211_ap_return_29),
    .ap_return_30(call_ret1_relu_1_fu_211_ap_return_30),
    .ap_return_31(call_ret1_relu_1_fu_211_ap_return_31),
    .ap_return_32(call_ret1_relu_1_fu_211_ap_return_32),
    .ap_return_33(call_ret1_relu_1_fu_211_ap_return_33),
    .ap_return_34(call_ret1_relu_1_fu_211_ap_return_34),
    .ap_return_35(call_ret1_relu_1_fu_211_ap_return_35),
    .ap_return_36(call_ret1_relu_1_fu_211_ap_return_36),
    .ap_return_37(call_ret1_relu_1_fu_211_ap_return_37),
    .ap_return_38(call_ret1_relu_1_fu_211_ap_return_38),
    .ap_return_39(call_ret1_relu_1_fu_211_ap_return_39),
    .ap_return_40(call_ret1_relu_1_fu_211_ap_return_40),
    .ap_return_41(call_ret1_relu_1_fu_211_ap_return_41),
    .ap_return_42(call_ret1_relu_1_fu_211_ap_return_42),
    .ap_return_43(call_ret1_relu_1_fu_211_ap_return_43),
    .ap_return_44(call_ret1_relu_1_fu_211_ap_return_44),
    .ap_return_45(call_ret1_relu_1_fu_211_ap_return_45),
    .ap_return_46(call_ret1_relu_1_fu_211_ap_return_46),
    .ap_return_47(call_ret1_relu_1_fu_211_ap_return_47),
    .ap_return_48(call_ret1_relu_1_fu_211_ap_return_48),
    .ap_return_49(call_ret1_relu_1_fu_211_ap_return_49)
);

relu call_ret3_relu_fu_265(
    .ap_ready(call_ret3_relu_fu_265_ap_ready),
    .data_0_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_0),
    .data_1_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_1),
    .data_2_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_2),
    .data_3_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_3),
    .data_4_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_4),
    .data_5_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_5),
    .data_6_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_6),
    .data_7_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_7),
    .data_8_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_8),
    .data_9_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_9),
    .data_10_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_10),
    .data_11_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_11),
    .data_12_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_12),
    .data_13_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_13),
    .data_14_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_14),
    .data_15_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_15),
    .data_16_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_16),
    .data_17_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_17),
    .data_18_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_18),
    .data_19_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_19),
    .data_20_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_20),
    .data_21_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_21),
    .data_22_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_22),
    .data_23_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_23),
    .data_24_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_24),
    .data_25_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_25),
    .data_26_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_26),
    .data_27_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_27),
    .data_28_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_28),
    .data_29_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_29),
    .data_30_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_30),
    .data_31_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_31),
    .data_32_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_32),
    .data_33_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_33),
    .data_34_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_34),
    .data_35_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_35),
    .data_36_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_36),
    .data_37_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_37),
    .data_38_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_38),
    .data_39_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_39),
    .data_40_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_40),
    .data_41_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_41),
    .data_42_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_42),
    .data_43_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_43),
    .data_44_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_44),
    .data_45_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_45),
    .data_46_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_46),
    .data_47_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_47),
    .data_48_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_48),
    .data_49_V_read(grp_dense_latency_0_0_0_1_fu_83_ap_return_49),
    .ap_return_0(call_ret3_relu_fu_265_ap_return_0),
    .ap_return_1(call_ret3_relu_fu_265_ap_return_1),
    .ap_return_2(call_ret3_relu_fu_265_ap_return_2),
    .ap_return_3(call_ret3_relu_fu_265_ap_return_3),
    .ap_return_4(call_ret3_relu_fu_265_ap_return_4),
    .ap_return_5(call_ret3_relu_fu_265_ap_return_5),
    .ap_return_6(call_ret3_relu_fu_265_ap_return_6),
    .ap_return_7(call_ret3_relu_fu_265_ap_return_7),
    .ap_return_8(call_ret3_relu_fu_265_ap_return_8),
    .ap_return_9(call_ret3_relu_fu_265_ap_return_9),
    .ap_return_10(call_ret3_relu_fu_265_ap_return_10),
    .ap_return_11(call_ret3_relu_fu_265_ap_return_11),
    .ap_return_12(call_ret3_relu_fu_265_ap_return_12),
    .ap_return_13(call_ret3_relu_fu_265_ap_return_13),
    .ap_return_14(call_ret3_relu_fu_265_ap_return_14),
    .ap_return_15(call_ret3_relu_fu_265_ap_return_15),
    .ap_return_16(call_ret3_relu_fu_265_ap_return_16),
    .ap_return_17(call_ret3_relu_fu_265_ap_return_17),
    .ap_return_18(call_ret3_relu_fu_265_ap_return_18),
    .ap_return_19(call_ret3_relu_fu_265_ap_return_19),
    .ap_return_20(call_ret3_relu_fu_265_ap_return_20),
    .ap_return_21(call_ret3_relu_fu_265_ap_return_21),
    .ap_return_22(call_ret3_relu_fu_265_ap_return_22),
    .ap_return_23(call_ret3_relu_fu_265_ap_return_23),
    .ap_return_24(call_ret3_relu_fu_265_ap_return_24),
    .ap_return_25(call_ret3_relu_fu_265_ap_return_25),
    .ap_return_26(call_ret3_relu_fu_265_ap_return_26),
    .ap_return_27(call_ret3_relu_fu_265_ap_return_27),
    .ap_return_28(call_ret3_relu_fu_265_ap_return_28),
    .ap_return_29(call_ret3_relu_fu_265_ap_return_29),
    .ap_return_30(call_ret3_relu_fu_265_ap_return_30),
    .ap_return_31(call_ret3_relu_fu_265_ap_return_31),
    .ap_return_32(call_ret3_relu_fu_265_ap_return_32),
    .ap_return_33(call_ret3_relu_fu_265_ap_return_33),
    .ap_return_34(call_ret3_relu_fu_265_ap_return_34),
    .ap_return_35(call_ret3_relu_fu_265_ap_return_35),
    .ap_return_36(call_ret3_relu_fu_265_ap_return_36),
    .ap_return_37(call_ret3_relu_fu_265_ap_return_37),
    .ap_return_38(call_ret3_relu_fu_265_ap_return_38),
    .ap_return_39(call_ret3_relu_fu_265_ap_return_39),
    .ap_return_40(call_ret3_relu_fu_265_ap_return_40),
    .ap_return_41(call_ret3_relu_fu_265_ap_return_41),
    .ap_return_42(call_ret3_relu_fu_265_ap_return_42),
    .ap_return_43(call_ret3_relu_fu_265_ap_return_43),
    .ap_return_44(call_ret3_relu_fu_265_ap_return_44),
    .ap_return_45(call_ret3_relu_fu_265_ap_return_45),
    .ap_return_46(call_ret3_relu_fu_265_ap_return_46),
    .ap_return_47(call_ret3_relu_fu_265_ap_return_47),
    .ap_return_48(call_ret3_relu_fu_265_ap_return_48),
    .ap_return_49(call_ret3_relu_fu_265_ap_return_49)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_latency_0_0_0_1_fu_83_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
            grp_dense_latency_0_0_0_1_fu_83_ap_start_reg <= 1'b1;
        end else if ((grp_dense_latency_0_0_0_1_fu_83_ap_ready == 1'b1)) begin
            grp_dense_latency_0_0_0_1_fu_83_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_latency_0_0_0_s_fu_143_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            grp_dense_latency_0_0_0_s_fu_143_ap_start_reg <= 1'b1;
        end else if ((grp_dense_latency_0_0_0_s_fu_143_ap_ready == 1'b1)) begin
            grp_dense_latency_0_0_0_s_fu_143_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_softmax_fu_197_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_softmax_fu_197_ap_start_reg <= 1'b1;
        end else if ((grp_softmax_fu_197_ap_ready == 1'b1)) begin
            grp_softmax_fu_197_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        input_V_ap_vld_preg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            input_V_ap_vld_preg <= 1'b0;
        end else if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0)) & (input_V_ap_vld == 1'b1))) begin
            input_V_ap_vld_preg <= input_V_ap_vld;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        input_V_preg <= 864'd0;
    end else begin
        if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0)) & (input_V_ap_vld == 1'b1))) begin
            input_V_preg <= input_V;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        const_size_in_1_ap_vld = 1'b1;
    end else begin
        const_size_in_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        const_size_out_1_ap_vld = 1'b1;
    end else begin
        const_size_out_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001_ignoreCallOp119) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp121) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp120) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001_ignoreCallOp122) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        grp_dense_latency_0_0_0_1_fu_83_ap_ce = 1'b1;
    end else begin
        grp_dense_latency_0_0_0_1_fu_83_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001_ignoreCallOp17) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp15) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp14) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001_ignoreCallOp16) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        grp_dense_latency_0_0_0_2_fu_137_ap_ce = 1'b1;
    end else begin
        grp_dense_latency_0_0_0_2_fu_137_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_dense_latency_0_0_0_2_fu_137_ap_start = 1'b1;
    end else begin
        grp_dense_latency_0_0_0_2_fu_137_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001_ignoreCallOp225) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp227) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp226) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001_ignoreCallOp224) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        grp_dense_latency_0_0_0_s_fu_143_ap_ce = 1'b1;
    end else begin
        grp_dense_latency_0_0_0_s_fu_143_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001_ignoreCallOp246) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp234) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001_ignoreCallOp235) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        grp_softmax_fu_197_ap_ce = 1'b1;
    end else begin
        grp_softmax_fu_197_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((input_V_ap_vld == 1'b1)) begin
        input_V_ap_vld_in_sig = input_V_ap_vld;
    end else begin
        input_V_ap_vld_in_sig = input_V_ap_vld_preg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_V_blk_n = input_V_ap_vld;
    end else begin
        input_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((input_V_ap_vld == 1'b1)) begin
        input_V_in_sig = input_V;
    end else begin
        input_V_in_sig = input_V_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer7_out_V_ap_vld = 1'b1;
    end else begin
        layer7_out_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((((1'b0 == ap_block_pp0_stage3_subdone) & (ap_reset_idle_pp0 == 1'b0)) | ((1'b0 == ap_block_pp0_stage3_subdone) & (ap_reset_idle_pp0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((ap_start == 1'b0) | (input_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp120 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((ap_start == 1'b0) | (input_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp14 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((ap_start == 1'b0) | (input_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp226 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((ap_start == 1'b0) | (input_V_ap_vld_in_sig == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((ap_start == 1'b0) | (input_V_ap_vld_in_sig == 1'b0)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001_ignoreCallOp121 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001_ignoreCallOp15 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001_ignoreCallOp227 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001_ignoreCallOp234 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001_ignoreCallOp122 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001_ignoreCallOp16 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001_ignoreCallOp224 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001_ignoreCallOp235 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001_ignoreCallOp119 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001_ignoreCallOp17 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001_ignoreCallOp225 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001_ignoreCallOp246 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage1_iter2_ignore_call11 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage1_iter2_ignore_call113 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage1_iter2_ignore_call215 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage1_iter2_ignore_call222 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage2_iter2_ignore_call11 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage2_iter2_ignore_call113 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage2_iter2_ignore_call215 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage2_iter2_ignore_call222 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage3_iter2_ignore_call11 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage3_iter2_ignore_call113 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage3_iter2_ignore_call215 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage3_iter2_ignore_call222 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | (input_V_ap_vld_in_sig == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call11 = ((ap_start == 1'b0) | (input_V_ap_vld_in_sig == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call113 = ((ap_start == 1'b0) | (input_V_ap_vld_in_sig == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call215 = ((ap_start == 1'b0) | (input_V_ap_vld_in_sig == 1'b0));
end

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0_ignore_call11 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0_ignore_call113 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0_ignore_call215 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0_ignore_call222 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0_ignore_call11 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0_ignore_call113 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0_ignore_call215 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0_ignore_call222 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0_ignore_call11 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0_ignore_call113 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0_ignore_call215 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0_ignore_call222 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1_ignore_call11 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1_ignore_call113 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1_ignore_call215 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter1_ignore_call11 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter1_ignore_call113 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter1_ignore_call215 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter1_ignore_call222 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage2_iter1_ignore_call11 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage2_iter1_ignore_call113 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage2_iter1_ignore_call215 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage2_iter1_ignore_call222 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage3_iter1_ignore_call11 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage3_iter1_ignore_call113 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage3_iter1_ignore_call215 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage3_iter1_ignore_call222 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter2_ignore_call11 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter2_ignore_call113 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter2_ignore_call215 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign const_size_in_1 = 16'd36;

assign const_size_out_1 = 16'd6;

assign grp_dense_latency_0_0_0_1_fu_83_ap_start = grp_dense_latency_0_0_0_1_fu_83_ap_start_reg;

assign grp_dense_latency_0_0_0_s_fu_143_ap_start = grp_dense_latency_0_0_0_s_fu_143_ap_start_reg;

assign grp_softmax_fu_197_ap_start = grp_softmax_fu_197_ap_start_reg;

assign layer7_out_V = grp_softmax_fu_197_ap_return;

endmodule //fpga_ANN50x50
