// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module product (
        ap_ready,
        a_V,
        w_V,
        ap_return
);


output   ap_ready;
input  [31:0] a_V;
input  [27:0] w_V;
output  [31:0] ap_return;

wire  signed [27:0] r_V_fu_34_p0;
wire  signed [31:0] r_V_fu_34_p1;
wire   [55:0] r_V_fu_34_p2;

assign ap_ready = 1'b1;

assign ap_return = {{r_V_fu_34_p2[55:24]}};

assign r_V_fu_34_p0 = w_V;

assign r_V_fu_34_p1 = a_V;

assign r_V_fu_34_p2 = ($signed(r_V_fu_34_p0) * $signed(r_V_fu_34_p1));

endmodule //product
