// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module product (
        ap_ready,
        a_V,
        w_V,
        ap_return
);


output   ap_ready;
input  [23:0] a_V;
input  [18:0] w_V;
output  [23:0] ap_return;

wire  signed [39:0] r_V_fu_43_p2;

fpga_ANN50x50_mul_mul_19s_24s_40_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 19 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 40 ))
fpga_ANN50x50_mul_mul_19s_24s_40_1_1_U1(
    .din0(w_V),
    .din1(a_V),
    .dout(r_V_fu_43_p2)
);

assign ap_ready = 1'b1;

assign ap_return = {{r_V_fu_43_p2[39:16]}};

endmodule //product
