// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module relu_1 (
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        data_12_V_read,
        data_13_V_read,
        data_14_V_read,
        data_15_V_read,
        data_16_V_read,
        data_17_V_read,
        data_18_V_read,
        data_19_V_read,
        data_20_V_read,
        data_21_V_read,
        data_22_V_read,
        data_23_V_read,
        data_24_V_read,
        data_25_V_read,
        data_26_V_read,
        data_27_V_read,
        data_28_V_read,
        data_29_V_read,
        data_30_V_read,
        data_31_V_read,
        data_32_V_read,
        data_33_V_read,
        data_34_V_read,
        data_35_V_read,
        data_36_V_read,
        data_37_V_read,
        data_38_V_read,
        data_39_V_read,
        data_40_V_read,
        data_41_V_read,
        data_42_V_read,
        data_43_V_read,
        data_44_V_read,
        data_45_V_read,
        data_46_V_read,
        data_47_V_read,
        data_48_V_read,
        data_49_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31,
        ap_return_32,
        ap_return_33,
        ap_return_34,
        ap_return_35,
        ap_return_36,
        ap_return_37,
        ap_return_38,
        ap_return_39,
        ap_return_40,
        ap_return_41,
        ap_return_42,
        ap_return_43,
        ap_return_44,
        ap_return_45,
        ap_return_46,
        ap_return_47,
        ap_return_48,
        ap_return_49
);


output   ap_ready;
input  [23:0] data_0_V_read;
input  [23:0] data_1_V_read;
input  [23:0] data_2_V_read;
input  [23:0] data_3_V_read;
input  [23:0] data_4_V_read;
input  [23:0] data_5_V_read;
input  [23:0] data_6_V_read;
input  [23:0] data_7_V_read;
input  [23:0] data_8_V_read;
input  [23:0] data_9_V_read;
input  [23:0] data_10_V_read;
input  [23:0] data_11_V_read;
input  [23:0] data_12_V_read;
input  [23:0] data_13_V_read;
input  [23:0] data_14_V_read;
input  [23:0] data_15_V_read;
input  [23:0] data_16_V_read;
input  [23:0] data_17_V_read;
input  [23:0] data_18_V_read;
input  [23:0] data_19_V_read;
input  [23:0] data_20_V_read;
input  [23:0] data_21_V_read;
input  [23:0] data_22_V_read;
input  [23:0] data_23_V_read;
input  [23:0] data_24_V_read;
input  [23:0] data_25_V_read;
input  [23:0] data_26_V_read;
input  [23:0] data_27_V_read;
input  [23:0] data_28_V_read;
input  [23:0] data_29_V_read;
input  [23:0] data_30_V_read;
input  [23:0] data_31_V_read;
input  [23:0] data_32_V_read;
input  [23:0] data_33_V_read;
input  [23:0] data_34_V_read;
input  [23:0] data_35_V_read;
input  [23:0] data_36_V_read;
input  [23:0] data_37_V_read;
input  [23:0] data_38_V_read;
input  [23:0] data_39_V_read;
input  [23:0] data_40_V_read;
input  [23:0] data_41_V_read;
input  [23:0] data_42_V_read;
input  [23:0] data_43_V_read;
input  [23:0] data_44_V_read;
input  [23:0] data_45_V_read;
input  [23:0] data_46_V_read;
input  [23:0] data_47_V_read;
input  [23:0] data_48_V_read;
input  [23:0] data_49_V_read;
output  [23:0] ap_return_0;
output  [23:0] ap_return_1;
output  [23:0] ap_return_2;
output  [23:0] ap_return_3;
output  [23:0] ap_return_4;
output  [23:0] ap_return_5;
output  [23:0] ap_return_6;
output  [23:0] ap_return_7;
output  [23:0] ap_return_8;
output  [23:0] ap_return_9;
output  [23:0] ap_return_10;
output  [23:0] ap_return_11;
output  [23:0] ap_return_12;
output  [23:0] ap_return_13;
output  [23:0] ap_return_14;
output  [23:0] ap_return_15;
output  [23:0] ap_return_16;
output  [23:0] ap_return_17;
output  [23:0] ap_return_18;
output  [23:0] ap_return_19;
output  [23:0] ap_return_20;
output  [23:0] ap_return_21;
output  [23:0] ap_return_22;
output  [23:0] ap_return_23;
output  [23:0] ap_return_24;
output  [23:0] ap_return_25;
output  [23:0] ap_return_26;
output  [23:0] ap_return_27;
output  [23:0] ap_return_28;
output  [23:0] ap_return_29;
output  [23:0] ap_return_30;
output  [23:0] ap_return_31;
output  [23:0] ap_return_32;
output  [23:0] ap_return_33;
output  [23:0] ap_return_34;
output  [23:0] ap_return_35;
output  [23:0] ap_return_36;
output  [23:0] ap_return_37;
output  [23:0] ap_return_38;
output  [23:0] ap_return_39;
output  [23:0] ap_return_40;
output  [23:0] ap_return_41;
output  [23:0] ap_return_42;
output  [23:0] ap_return_43;
output  [23:0] ap_return_44;
output  [23:0] ap_return_45;
output  [23:0] ap_return_46;
output  [23:0] ap_return_47;
output  [23:0] ap_return_48;
output  [23:0] ap_return_49;

wire   [0:0] icmp_ln1494_fu_424_p2;
wire   [22:0] trunc_ln83_fu_430_p1;
wire   [22:0] select_ln83_fu_434_p3;
wire   [0:0] icmp_ln1494_1_fu_446_p2;
wire   [22:0] trunc_ln83_1_fu_452_p1;
wire   [22:0] select_ln83_1_fu_456_p3;
wire   [0:0] icmp_ln1494_2_fu_468_p2;
wire   [22:0] trunc_ln83_2_fu_474_p1;
wire   [22:0] select_ln83_2_fu_478_p3;
wire   [0:0] icmp_ln1494_3_fu_490_p2;
wire   [22:0] trunc_ln83_3_fu_496_p1;
wire   [22:0] select_ln83_3_fu_500_p3;
wire   [0:0] icmp_ln1494_4_fu_512_p2;
wire   [22:0] trunc_ln83_4_fu_518_p1;
wire   [22:0] select_ln83_4_fu_522_p3;
wire   [0:0] icmp_ln1494_5_fu_534_p2;
wire   [22:0] trunc_ln83_5_fu_540_p1;
wire   [22:0] select_ln83_5_fu_544_p3;
wire   [0:0] icmp_ln1494_6_fu_556_p2;
wire   [22:0] trunc_ln83_6_fu_562_p1;
wire   [22:0] select_ln83_6_fu_566_p3;
wire   [0:0] icmp_ln1494_7_fu_578_p2;
wire   [22:0] trunc_ln83_7_fu_584_p1;
wire   [22:0] select_ln83_7_fu_588_p3;
wire   [0:0] icmp_ln1494_8_fu_600_p2;
wire   [22:0] trunc_ln83_8_fu_606_p1;
wire   [22:0] select_ln83_8_fu_610_p3;
wire   [0:0] icmp_ln1494_9_fu_622_p2;
wire   [22:0] trunc_ln83_9_fu_628_p1;
wire   [22:0] select_ln83_9_fu_632_p3;
wire   [0:0] icmp_ln1494_10_fu_644_p2;
wire   [22:0] trunc_ln83_10_fu_650_p1;
wire   [22:0] select_ln83_10_fu_654_p3;
wire   [0:0] icmp_ln1494_11_fu_666_p2;
wire   [22:0] trunc_ln83_11_fu_672_p1;
wire   [22:0] select_ln83_11_fu_676_p3;
wire   [0:0] icmp_ln1494_12_fu_688_p2;
wire   [22:0] trunc_ln83_12_fu_694_p1;
wire   [22:0] select_ln83_12_fu_698_p3;
wire   [0:0] icmp_ln1494_13_fu_710_p2;
wire   [22:0] trunc_ln83_13_fu_716_p1;
wire   [22:0] select_ln83_13_fu_720_p3;
wire   [0:0] icmp_ln1494_14_fu_732_p2;
wire   [22:0] trunc_ln83_14_fu_738_p1;
wire   [22:0] select_ln83_14_fu_742_p3;
wire   [0:0] icmp_ln1494_15_fu_754_p2;
wire   [22:0] trunc_ln83_15_fu_760_p1;
wire   [22:0] select_ln83_15_fu_764_p3;
wire   [0:0] icmp_ln1494_16_fu_776_p2;
wire   [22:0] trunc_ln83_16_fu_782_p1;
wire   [22:0] select_ln83_16_fu_786_p3;
wire   [0:0] icmp_ln1494_17_fu_798_p2;
wire   [22:0] trunc_ln83_17_fu_804_p1;
wire   [22:0] select_ln83_17_fu_808_p3;
wire   [0:0] icmp_ln1494_18_fu_820_p2;
wire   [22:0] trunc_ln83_18_fu_826_p1;
wire   [22:0] select_ln83_18_fu_830_p3;
wire   [0:0] icmp_ln1494_19_fu_842_p2;
wire   [22:0] trunc_ln83_19_fu_848_p1;
wire   [22:0] select_ln83_19_fu_852_p3;
wire   [0:0] icmp_ln1494_20_fu_864_p2;
wire   [22:0] trunc_ln83_20_fu_870_p1;
wire   [22:0] select_ln83_20_fu_874_p3;
wire   [0:0] icmp_ln1494_21_fu_886_p2;
wire   [22:0] trunc_ln83_21_fu_892_p1;
wire   [22:0] select_ln83_21_fu_896_p3;
wire   [0:0] icmp_ln1494_22_fu_908_p2;
wire   [22:0] trunc_ln83_22_fu_914_p1;
wire   [22:0] select_ln83_22_fu_918_p3;
wire   [0:0] icmp_ln1494_23_fu_930_p2;
wire   [22:0] trunc_ln83_23_fu_936_p1;
wire   [22:0] select_ln83_23_fu_940_p3;
wire   [0:0] icmp_ln1494_24_fu_952_p2;
wire   [22:0] trunc_ln83_24_fu_958_p1;
wire   [22:0] select_ln83_24_fu_962_p3;
wire   [0:0] icmp_ln1494_25_fu_974_p2;
wire   [22:0] trunc_ln83_25_fu_980_p1;
wire   [22:0] select_ln83_25_fu_984_p3;
wire   [0:0] icmp_ln1494_26_fu_996_p2;
wire   [22:0] trunc_ln83_26_fu_1002_p1;
wire   [22:0] select_ln83_26_fu_1006_p3;
wire   [0:0] icmp_ln1494_27_fu_1018_p2;
wire   [22:0] trunc_ln83_27_fu_1024_p1;
wire   [22:0] select_ln83_27_fu_1028_p3;
wire   [0:0] icmp_ln1494_28_fu_1040_p2;
wire   [22:0] trunc_ln83_28_fu_1046_p1;
wire   [22:0] select_ln83_28_fu_1050_p3;
wire   [0:0] icmp_ln1494_29_fu_1062_p2;
wire   [22:0] trunc_ln83_29_fu_1068_p1;
wire   [22:0] select_ln83_29_fu_1072_p3;
wire   [0:0] icmp_ln1494_30_fu_1084_p2;
wire   [22:0] trunc_ln83_30_fu_1090_p1;
wire   [22:0] select_ln83_30_fu_1094_p3;
wire   [0:0] icmp_ln1494_31_fu_1106_p2;
wire   [22:0] trunc_ln83_31_fu_1112_p1;
wire   [22:0] select_ln83_31_fu_1116_p3;
wire   [0:0] icmp_ln1494_32_fu_1128_p2;
wire   [22:0] trunc_ln83_32_fu_1134_p1;
wire   [22:0] select_ln83_32_fu_1138_p3;
wire   [0:0] icmp_ln1494_33_fu_1150_p2;
wire   [22:0] trunc_ln83_33_fu_1156_p1;
wire   [22:0] select_ln83_33_fu_1160_p3;
wire   [0:0] icmp_ln1494_34_fu_1172_p2;
wire   [22:0] trunc_ln83_34_fu_1178_p1;
wire   [22:0] select_ln83_34_fu_1182_p3;
wire   [0:0] icmp_ln1494_35_fu_1194_p2;
wire   [22:0] trunc_ln83_35_fu_1200_p1;
wire   [22:0] select_ln83_35_fu_1204_p3;
wire   [0:0] icmp_ln1494_36_fu_1216_p2;
wire   [22:0] trunc_ln83_36_fu_1222_p1;
wire   [22:0] select_ln83_36_fu_1226_p3;
wire   [0:0] icmp_ln1494_37_fu_1238_p2;
wire   [22:0] trunc_ln83_37_fu_1244_p1;
wire   [22:0] select_ln83_37_fu_1248_p3;
wire   [0:0] icmp_ln1494_38_fu_1260_p2;
wire   [22:0] trunc_ln83_38_fu_1266_p1;
wire   [22:0] select_ln83_38_fu_1270_p3;
wire   [0:0] icmp_ln1494_39_fu_1282_p2;
wire   [22:0] trunc_ln83_39_fu_1288_p1;
wire   [22:0] select_ln83_39_fu_1292_p3;
wire   [0:0] icmp_ln1494_40_fu_1304_p2;
wire   [22:0] trunc_ln83_40_fu_1310_p1;
wire   [22:0] select_ln83_40_fu_1314_p3;
wire   [0:0] icmp_ln1494_41_fu_1326_p2;
wire   [22:0] trunc_ln83_41_fu_1332_p1;
wire   [22:0] select_ln83_41_fu_1336_p3;
wire   [0:0] icmp_ln1494_42_fu_1348_p2;
wire   [22:0] trunc_ln83_42_fu_1354_p1;
wire   [22:0] select_ln83_42_fu_1358_p3;
wire   [0:0] icmp_ln1494_43_fu_1370_p2;
wire   [22:0] trunc_ln83_43_fu_1376_p1;
wire   [22:0] select_ln83_43_fu_1380_p3;
wire   [0:0] icmp_ln1494_44_fu_1392_p2;
wire   [22:0] trunc_ln83_44_fu_1398_p1;
wire   [22:0] select_ln83_44_fu_1402_p3;
wire   [0:0] icmp_ln1494_45_fu_1414_p2;
wire   [22:0] trunc_ln83_45_fu_1420_p1;
wire   [22:0] select_ln83_45_fu_1424_p3;
wire   [0:0] icmp_ln1494_46_fu_1436_p2;
wire   [22:0] trunc_ln83_46_fu_1442_p1;
wire   [22:0] select_ln83_46_fu_1446_p3;
wire   [0:0] icmp_ln1494_47_fu_1458_p2;
wire   [22:0] trunc_ln83_47_fu_1464_p1;
wire   [22:0] select_ln83_47_fu_1468_p3;
wire   [0:0] icmp_ln1494_48_fu_1480_p2;
wire   [22:0] trunc_ln83_48_fu_1486_p1;
wire   [22:0] select_ln83_48_fu_1490_p3;
wire   [0:0] icmp_ln1494_49_fu_1502_p2;
wire   [22:0] trunc_ln83_49_fu_1508_p1;
wire   [22:0] select_ln83_49_fu_1512_p3;
wire   [23:0] zext_ln83_fu_442_p1;
wire   [23:0] zext_ln83_1_fu_464_p1;
wire   [23:0] zext_ln83_2_fu_486_p1;
wire   [23:0] zext_ln83_3_fu_508_p1;
wire   [23:0] zext_ln83_4_fu_530_p1;
wire   [23:0] zext_ln83_5_fu_552_p1;
wire   [23:0] zext_ln83_6_fu_574_p1;
wire   [23:0] zext_ln83_7_fu_596_p1;
wire   [23:0] zext_ln83_8_fu_618_p1;
wire   [23:0] zext_ln83_9_fu_640_p1;
wire   [23:0] zext_ln83_10_fu_662_p1;
wire   [23:0] zext_ln83_11_fu_684_p1;
wire   [23:0] zext_ln83_12_fu_706_p1;
wire   [23:0] zext_ln83_13_fu_728_p1;
wire   [23:0] zext_ln83_14_fu_750_p1;
wire   [23:0] zext_ln83_15_fu_772_p1;
wire   [23:0] zext_ln83_16_fu_794_p1;
wire   [23:0] zext_ln83_17_fu_816_p1;
wire   [23:0] zext_ln83_18_fu_838_p1;
wire   [23:0] zext_ln83_19_fu_860_p1;
wire   [23:0] zext_ln83_20_fu_882_p1;
wire   [23:0] zext_ln83_21_fu_904_p1;
wire   [23:0] zext_ln83_22_fu_926_p1;
wire   [23:0] zext_ln83_23_fu_948_p1;
wire   [23:0] zext_ln83_24_fu_970_p1;
wire   [23:0] zext_ln83_25_fu_992_p1;
wire   [23:0] zext_ln83_26_fu_1014_p1;
wire   [23:0] zext_ln83_27_fu_1036_p1;
wire   [23:0] zext_ln83_28_fu_1058_p1;
wire   [23:0] zext_ln83_29_fu_1080_p1;
wire   [23:0] zext_ln83_30_fu_1102_p1;
wire   [23:0] zext_ln83_31_fu_1124_p1;
wire   [23:0] zext_ln83_32_fu_1146_p1;
wire   [23:0] zext_ln83_33_fu_1168_p1;
wire   [23:0] zext_ln83_34_fu_1190_p1;
wire   [23:0] zext_ln83_35_fu_1212_p1;
wire   [23:0] zext_ln83_36_fu_1234_p1;
wire   [23:0] zext_ln83_37_fu_1256_p1;
wire   [23:0] zext_ln83_38_fu_1278_p1;
wire   [23:0] zext_ln83_39_fu_1300_p1;
wire   [23:0] zext_ln83_40_fu_1322_p1;
wire   [23:0] zext_ln83_41_fu_1344_p1;
wire   [23:0] zext_ln83_42_fu_1366_p1;
wire   [23:0] zext_ln83_43_fu_1388_p1;
wire   [23:0] zext_ln83_44_fu_1410_p1;
wire   [23:0] zext_ln83_45_fu_1432_p1;
wire   [23:0] zext_ln83_46_fu_1454_p1;
wire   [23:0] zext_ln83_47_fu_1476_p1;
wire   [23:0] zext_ln83_48_fu_1498_p1;
wire   [23:0] zext_ln83_49_fu_1520_p1;

assign ap_ready = 1'b1;

assign ap_return_0 = zext_ln83_fu_442_p1;

assign ap_return_1 = zext_ln83_1_fu_464_p1;

assign ap_return_10 = zext_ln83_10_fu_662_p1;

assign ap_return_11 = zext_ln83_11_fu_684_p1;

assign ap_return_12 = zext_ln83_12_fu_706_p1;

assign ap_return_13 = zext_ln83_13_fu_728_p1;

assign ap_return_14 = zext_ln83_14_fu_750_p1;

assign ap_return_15 = zext_ln83_15_fu_772_p1;

assign ap_return_16 = zext_ln83_16_fu_794_p1;

assign ap_return_17 = zext_ln83_17_fu_816_p1;

assign ap_return_18 = zext_ln83_18_fu_838_p1;

assign ap_return_19 = zext_ln83_19_fu_860_p1;

assign ap_return_2 = zext_ln83_2_fu_486_p1;

assign ap_return_20 = zext_ln83_20_fu_882_p1;

assign ap_return_21 = zext_ln83_21_fu_904_p1;

assign ap_return_22 = zext_ln83_22_fu_926_p1;

assign ap_return_23 = zext_ln83_23_fu_948_p1;

assign ap_return_24 = zext_ln83_24_fu_970_p1;

assign ap_return_25 = zext_ln83_25_fu_992_p1;

assign ap_return_26 = zext_ln83_26_fu_1014_p1;

assign ap_return_27 = zext_ln83_27_fu_1036_p1;

assign ap_return_28 = zext_ln83_28_fu_1058_p1;

assign ap_return_29 = zext_ln83_29_fu_1080_p1;

assign ap_return_3 = zext_ln83_3_fu_508_p1;

assign ap_return_30 = zext_ln83_30_fu_1102_p1;

assign ap_return_31 = zext_ln83_31_fu_1124_p1;

assign ap_return_32 = zext_ln83_32_fu_1146_p1;

assign ap_return_33 = zext_ln83_33_fu_1168_p1;

assign ap_return_34 = zext_ln83_34_fu_1190_p1;

assign ap_return_35 = zext_ln83_35_fu_1212_p1;

assign ap_return_36 = zext_ln83_36_fu_1234_p1;

assign ap_return_37 = zext_ln83_37_fu_1256_p1;

assign ap_return_38 = zext_ln83_38_fu_1278_p1;

assign ap_return_39 = zext_ln83_39_fu_1300_p1;

assign ap_return_4 = zext_ln83_4_fu_530_p1;

assign ap_return_40 = zext_ln83_40_fu_1322_p1;

assign ap_return_41 = zext_ln83_41_fu_1344_p1;

assign ap_return_42 = zext_ln83_42_fu_1366_p1;

assign ap_return_43 = zext_ln83_43_fu_1388_p1;

assign ap_return_44 = zext_ln83_44_fu_1410_p1;

assign ap_return_45 = zext_ln83_45_fu_1432_p1;

assign ap_return_46 = zext_ln83_46_fu_1454_p1;

assign ap_return_47 = zext_ln83_47_fu_1476_p1;

assign ap_return_48 = zext_ln83_48_fu_1498_p1;

assign ap_return_49 = zext_ln83_49_fu_1520_p1;

assign ap_return_5 = zext_ln83_5_fu_552_p1;

assign ap_return_6 = zext_ln83_6_fu_574_p1;

assign ap_return_7 = zext_ln83_7_fu_596_p1;

assign ap_return_8 = zext_ln83_8_fu_618_p1;

assign ap_return_9 = zext_ln83_9_fu_640_p1;

assign icmp_ln1494_10_fu_644_p2 = (($signed(data_10_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_11_fu_666_p2 = (($signed(data_11_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_12_fu_688_p2 = (($signed(data_12_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_13_fu_710_p2 = (($signed(data_13_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_14_fu_732_p2 = (($signed(data_14_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_15_fu_754_p2 = (($signed(data_15_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_16_fu_776_p2 = (($signed(data_16_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_17_fu_798_p2 = (($signed(data_17_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_18_fu_820_p2 = (($signed(data_18_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_19_fu_842_p2 = (($signed(data_19_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_1_fu_446_p2 = (($signed(data_1_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_20_fu_864_p2 = (($signed(data_20_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_21_fu_886_p2 = (($signed(data_21_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_22_fu_908_p2 = (($signed(data_22_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_23_fu_930_p2 = (($signed(data_23_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_24_fu_952_p2 = (($signed(data_24_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_25_fu_974_p2 = (($signed(data_25_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_26_fu_996_p2 = (($signed(data_26_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_27_fu_1018_p2 = (($signed(data_27_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_28_fu_1040_p2 = (($signed(data_28_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_29_fu_1062_p2 = (($signed(data_29_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_2_fu_468_p2 = (($signed(data_2_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_30_fu_1084_p2 = (($signed(data_30_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_31_fu_1106_p2 = (($signed(data_31_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_32_fu_1128_p2 = (($signed(data_32_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_33_fu_1150_p2 = (($signed(data_33_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_34_fu_1172_p2 = (($signed(data_34_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_35_fu_1194_p2 = (($signed(data_35_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_36_fu_1216_p2 = (($signed(data_36_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_37_fu_1238_p2 = (($signed(data_37_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_38_fu_1260_p2 = (($signed(data_38_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_39_fu_1282_p2 = (($signed(data_39_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_3_fu_490_p2 = (($signed(data_3_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_40_fu_1304_p2 = (($signed(data_40_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_41_fu_1326_p2 = (($signed(data_41_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_42_fu_1348_p2 = (($signed(data_42_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_43_fu_1370_p2 = (($signed(data_43_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_44_fu_1392_p2 = (($signed(data_44_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_45_fu_1414_p2 = (($signed(data_45_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_46_fu_1436_p2 = (($signed(data_46_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_47_fu_1458_p2 = (($signed(data_47_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_48_fu_1480_p2 = (($signed(data_48_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_49_fu_1502_p2 = (($signed(data_49_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_4_fu_512_p2 = (($signed(data_4_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_5_fu_534_p2 = (($signed(data_5_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_6_fu_556_p2 = (($signed(data_6_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_7_fu_578_p2 = (($signed(data_7_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_8_fu_600_p2 = (($signed(data_8_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_9_fu_622_p2 = (($signed(data_9_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_fu_424_p2 = (($signed(data_0_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign select_ln83_10_fu_654_p3 = ((icmp_ln1494_10_fu_644_p2[0:0] === 1'b1) ? trunc_ln83_10_fu_650_p1 : 23'd0);

assign select_ln83_11_fu_676_p3 = ((icmp_ln1494_11_fu_666_p2[0:0] === 1'b1) ? trunc_ln83_11_fu_672_p1 : 23'd0);

assign select_ln83_12_fu_698_p3 = ((icmp_ln1494_12_fu_688_p2[0:0] === 1'b1) ? trunc_ln83_12_fu_694_p1 : 23'd0);

assign select_ln83_13_fu_720_p3 = ((icmp_ln1494_13_fu_710_p2[0:0] === 1'b1) ? trunc_ln83_13_fu_716_p1 : 23'd0);

assign select_ln83_14_fu_742_p3 = ((icmp_ln1494_14_fu_732_p2[0:0] === 1'b1) ? trunc_ln83_14_fu_738_p1 : 23'd0);

assign select_ln83_15_fu_764_p3 = ((icmp_ln1494_15_fu_754_p2[0:0] === 1'b1) ? trunc_ln83_15_fu_760_p1 : 23'd0);

assign select_ln83_16_fu_786_p3 = ((icmp_ln1494_16_fu_776_p2[0:0] === 1'b1) ? trunc_ln83_16_fu_782_p1 : 23'd0);

assign select_ln83_17_fu_808_p3 = ((icmp_ln1494_17_fu_798_p2[0:0] === 1'b1) ? trunc_ln83_17_fu_804_p1 : 23'd0);

assign select_ln83_18_fu_830_p3 = ((icmp_ln1494_18_fu_820_p2[0:0] === 1'b1) ? trunc_ln83_18_fu_826_p1 : 23'd0);

assign select_ln83_19_fu_852_p3 = ((icmp_ln1494_19_fu_842_p2[0:0] === 1'b1) ? trunc_ln83_19_fu_848_p1 : 23'd0);

assign select_ln83_1_fu_456_p3 = ((icmp_ln1494_1_fu_446_p2[0:0] === 1'b1) ? trunc_ln83_1_fu_452_p1 : 23'd0);

assign select_ln83_20_fu_874_p3 = ((icmp_ln1494_20_fu_864_p2[0:0] === 1'b1) ? trunc_ln83_20_fu_870_p1 : 23'd0);

assign select_ln83_21_fu_896_p3 = ((icmp_ln1494_21_fu_886_p2[0:0] === 1'b1) ? trunc_ln83_21_fu_892_p1 : 23'd0);

assign select_ln83_22_fu_918_p3 = ((icmp_ln1494_22_fu_908_p2[0:0] === 1'b1) ? trunc_ln83_22_fu_914_p1 : 23'd0);

assign select_ln83_23_fu_940_p3 = ((icmp_ln1494_23_fu_930_p2[0:0] === 1'b1) ? trunc_ln83_23_fu_936_p1 : 23'd0);

assign select_ln83_24_fu_962_p3 = ((icmp_ln1494_24_fu_952_p2[0:0] === 1'b1) ? trunc_ln83_24_fu_958_p1 : 23'd0);

assign select_ln83_25_fu_984_p3 = ((icmp_ln1494_25_fu_974_p2[0:0] === 1'b1) ? trunc_ln83_25_fu_980_p1 : 23'd0);

assign select_ln83_26_fu_1006_p3 = ((icmp_ln1494_26_fu_996_p2[0:0] === 1'b1) ? trunc_ln83_26_fu_1002_p1 : 23'd0);

assign select_ln83_27_fu_1028_p3 = ((icmp_ln1494_27_fu_1018_p2[0:0] === 1'b1) ? trunc_ln83_27_fu_1024_p1 : 23'd0);

assign select_ln83_28_fu_1050_p3 = ((icmp_ln1494_28_fu_1040_p2[0:0] === 1'b1) ? trunc_ln83_28_fu_1046_p1 : 23'd0);

assign select_ln83_29_fu_1072_p3 = ((icmp_ln1494_29_fu_1062_p2[0:0] === 1'b1) ? trunc_ln83_29_fu_1068_p1 : 23'd0);

assign select_ln83_2_fu_478_p3 = ((icmp_ln1494_2_fu_468_p2[0:0] === 1'b1) ? trunc_ln83_2_fu_474_p1 : 23'd0);

assign select_ln83_30_fu_1094_p3 = ((icmp_ln1494_30_fu_1084_p2[0:0] === 1'b1) ? trunc_ln83_30_fu_1090_p1 : 23'd0);

assign select_ln83_31_fu_1116_p3 = ((icmp_ln1494_31_fu_1106_p2[0:0] === 1'b1) ? trunc_ln83_31_fu_1112_p1 : 23'd0);

assign select_ln83_32_fu_1138_p3 = ((icmp_ln1494_32_fu_1128_p2[0:0] === 1'b1) ? trunc_ln83_32_fu_1134_p1 : 23'd0);

assign select_ln83_33_fu_1160_p3 = ((icmp_ln1494_33_fu_1150_p2[0:0] === 1'b1) ? trunc_ln83_33_fu_1156_p1 : 23'd0);

assign select_ln83_34_fu_1182_p3 = ((icmp_ln1494_34_fu_1172_p2[0:0] === 1'b1) ? trunc_ln83_34_fu_1178_p1 : 23'd0);

assign select_ln83_35_fu_1204_p3 = ((icmp_ln1494_35_fu_1194_p2[0:0] === 1'b1) ? trunc_ln83_35_fu_1200_p1 : 23'd0);

assign select_ln83_36_fu_1226_p3 = ((icmp_ln1494_36_fu_1216_p2[0:0] === 1'b1) ? trunc_ln83_36_fu_1222_p1 : 23'd0);

assign select_ln83_37_fu_1248_p3 = ((icmp_ln1494_37_fu_1238_p2[0:0] === 1'b1) ? trunc_ln83_37_fu_1244_p1 : 23'd0);

assign select_ln83_38_fu_1270_p3 = ((icmp_ln1494_38_fu_1260_p2[0:0] === 1'b1) ? trunc_ln83_38_fu_1266_p1 : 23'd0);

assign select_ln83_39_fu_1292_p3 = ((icmp_ln1494_39_fu_1282_p2[0:0] === 1'b1) ? trunc_ln83_39_fu_1288_p1 : 23'd0);

assign select_ln83_3_fu_500_p3 = ((icmp_ln1494_3_fu_490_p2[0:0] === 1'b1) ? trunc_ln83_3_fu_496_p1 : 23'd0);

assign select_ln83_40_fu_1314_p3 = ((icmp_ln1494_40_fu_1304_p2[0:0] === 1'b1) ? trunc_ln83_40_fu_1310_p1 : 23'd0);

assign select_ln83_41_fu_1336_p3 = ((icmp_ln1494_41_fu_1326_p2[0:0] === 1'b1) ? trunc_ln83_41_fu_1332_p1 : 23'd0);

assign select_ln83_42_fu_1358_p3 = ((icmp_ln1494_42_fu_1348_p2[0:0] === 1'b1) ? trunc_ln83_42_fu_1354_p1 : 23'd0);

assign select_ln83_43_fu_1380_p3 = ((icmp_ln1494_43_fu_1370_p2[0:0] === 1'b1) ? trunc_ln83_43_fu_1376_p1 : 23'd0);

assign select_ln83_44_fu_1402_p3 = ((icmp_ln1494_44_fu_1392_p2[0:0] === 1'b1) ? trunc_ln83_44_fu_1398_p1 : 23'd0);

assign select_ln83_45_fu_1424_p3 = ((icmp_ln1494_45_fu_1414_p2[0:0] === 1'b1) ? trunc_ln83_45_fu_1420_p1 : 23'd0);

assign select_ln83_46_fu_1446_p3 = ((icmp_ln1494_46_fu_1436_p2[0:0] === 1'b1) ? trunc_ln83_46_fu_1442_p1 : 23'd0);

assign select_ln83_47_fu_1468_p3 = ((icmp_ln1494_47_fu_1458_p2[0:0] === 1'b1) ? trunc_ln83_47_fu_1464_p1 : 23'd0);

assign select_ln83_48_fu_1490_p3 = ((icmp_ln1494_48_fu_1480_p2[0:0] === 1'b1) ? trunc_ln83_48_fu_1486_p1 : 23'd0);

assign select_ln83_49_fu_1512_p3 = ((icmp_ln1494_49_fu_1502_p2[0:0] === 1'b1) ? trunc_ln83_49_fu_1508_p1 : 23'd0);

assign select_ln83_4_fu_522_p3 = ((icmp_ln1494_4_fu_512_p2[0:0] === 1'b1) ? trunc_ln83_4_fu_518_p1 : 23'd0);

assign select_ln83_5_fu_544_p3 = ((icmp_ln1494_5_fu_534_p2[0:0] === 1'b1) ? trunc_ln83_5_fu_540_p1 : 23'd0);

assign select_ln83_6_fu_566_p3 = ((icmp_ln1494_6_fu_556_p2[0:0] === 1'b1) ? trunc_ln83_6_fu_562_p1 : 23'd0);

assign select_ln83_7_fu_588_p3 = ((icmp_ln1494_7_fu_578_p2[0:0] === 1'b1) ? trunc_ln83_7_fu_584_p1 : 23'd0);

assign select_ln83_8_fu_610_p3 = ((icmp_ln1494_8_fu_600_p2[0:0] === 1'b1) ? trunc_ln83_8_fu_606_p1 : 23'd0);

assign select_ln83_9_fu_632_p3 = ((icmp_ln1494_9_fu_622_p2[0:0] === 1'b1) ? trunc_ln83_9_fu_628_p1 : 23'd0);

assign select_ln83_fu_434_p3 = ((icmp_ln1494_fu_424_p2[0:0] === 1'b1) ? trunc_ln83_fu_430_p1 : 23'd0);

assign trunc_ln83_10_fu_650_p1 = data_10_V_read[22:0];

assign trunc_ln83_11_fu_672_p1 = data_11_V_read[22:0];

assign trunc_ln83_12_fu_694_p1 = data_12_V_read[22:0];

assign trunc_ln83_13_fu_716_p1 = data_13_V_read[22:0];

assign trunc_ln83_14_fu_738_p1 = data_14_V_read[22:0];

assign trunc_ln83_15_fu_760_p1 = data_15_V_read[22:0];

assign trunc_ln83_16_fu_782_p1 = data_16_V_read[22:0];

assign trunc_ln83_17_fu_804_p1 = data_17_V_read[22:0];

assign trunc_ln83_18_fu_826_p1 = data_18_V_read[22:0];

assign trunc_ln83_19_fu_848_p1 = data_19_V_read[22:0];

assign trunc_ln83_1_fu_452_p1 = data_1_V_read[22:0];

assign trunc_ln83_20_fu_870_p1 = data_20_V_read[22:0];

assign trunc_ln83_21_fu_892_p1 = data_21_V_read[22:0];

assign trunc_ln83_22_fu_914_p1 = data_22_V_read[22:0];

assign trunc_ln83_23_fu_936_p1 = data_23_V_read[22:0];

assign trunc_ln83_24_fu_958_p1 = data_24_V_read[22:0];

assign trunc_ln83_25_fu_980_p1 = data_25_V_read[22:0];

assign trunc_ln83_26_fu_1002_p1 = data_26_V_read[22:0];

assign trunc_ln83_27_fu_1024_p1 = data_27_V_read[22:0];

assign trunc_ln83_28_fu_1046_p1 = data_28_V_read[22:0];

assign trunc_ln83_29_fu_1068_p1 = data_29_V_read[22:0];

assign trunc_ln83_2_fu_474_p1 = data_2_V_read[22:0];

assign trunc_ln83_30_fu_1090_p1 = data_30_V_read[22:0];

assign trunc_ln83_31_fu_1112_p1 = data_31_V_read[22:0];

assign trunc_ln83_32_fu_1134_p1 = data_32_V_read[22:0];

assign trunc_ln83_33_fu_1156_p1 = data_33_V_read[22:0];

assign trunc_ln83_34_fu_1178_p1 = data_34_V_read[22:0];

assign trunc_ln83_35_fu_1200_p1 = data_35_V_read[22:0];

assign trunc_ln83_36_fu_1222_p1 = data_36_V_read[22:0];

assign trunc_ln83_37_fu_1244_p1 = data_37_V_read[22:0];

assign trunc_ln83_38_fu_1266_p1 = data_38_V_read[22:0];

assign trunc_ln83_39_fu_1288_p1 = data_39_V_read[22:0];

assign trunc_ln83_3_fu_496_p1 = data_3_V_read[22:0];

assign trunc_ln83_40_fu_1310_p1 = data_40_V_read[22:0];

assign trunc_ln83_41_fu_1332_p1 = data_41_V_read[22:0];

assign trunc_ln83_42_fu_1354_p1 = data_42_V_read[22:0];

assign trunc_ln83_43_fu_1376_p1 = data_43_V_read[22:0];

assign trunc_ln83_44_fu_1398_p1 = data_44_V_read[22:0];

assign trunc_ln83_45_fu_1420_p1 = data_45_V_read[22:0];

assign trunc_ln83_46_fu_1442_p1 = data_46_V_read[22:0];

assign trunc_ln83_47_fu_1464_p1 = data_47_V_read[22:0];

assign trunc_ln83_48_fu_1486_p1 = data_48_V_read[22:0];

assign trunc_ln83_49_fu_1508_p1 = data_49_V_read[22:0];

assign trunc_ln83_4_fu_518_p1 = data_4_V_read[22:0];

assign trunc_ln83_5_fu_540_p1 = data_5_V_read[22:0];

assign trunc_ln83_6_fu_562_p1 = data_6_V_read[22:0];

assign trunc_ln83_7_fu_584_p1 = data_7_V_read[22:0];

assign trunc_ln83_8_fu_606_p1 = data_8_V_read[22:0];

assign trunc_ln83_9_fu_628_p1 = data_9_V_read[22:0];

assign trunc_ln83_fu_430_p1 = data_0_V_read[22:0];

assign zext_ln83_10_fu_662_p1 = select_ln83_10_fu_654_p3;

assign zext_ln83_11_fu_684_p1 = select_ln83_11_fu_676_p3;

assign zext_ln83_12_fu_706_p1 = select_ln83_12_fu_698_p3;

assign zext_ln83_13_fu_728_p1 = select_ln83_13_fu_720_p3;

assign zext_ln83_14_fu_750_p1 = select_ln83_14_fu_742_p3;

assign zext_ln83_15_fu_772_p1 = select_ln83_15_fu_764_p3;

assign zext_ln83_16_fu_794_p1 = select_ln83_16_fu_786_p3;

assign zext_ln83_17_fu_816_p1 = select_ln83_17_fu_808_p3;

assign zext_ln83_18_fu_838_p1 = select_ln83_18_fu_830_p3;

assign zext_ln83_19_fu_860_p1 = select_ln83_19_fu_852_p3;

assign zext_ln83_1_fu_464_p1 = select_ln83_1_fu_456_p3;

assign zext_ln83_20_fu_882_p1 = select_ln83_20_fu_874_p3;

assign zext_ln83_21_fu_904_p1 = select_ln83_21_fu_896_p3;

assign zext_ln83_22_fu_926_p1 = select_ln83_22_fu_918_p3;

assign zext_ln83_23_fu_948_p1 = select_ln83_23_fu_940_p3;

assign zext_ln83_24_fu_970_p1 = select_ln83_24_fu_962_p3;

assign zext_ln83_25_fu_992_p1 = select_ln83_25_fu_984_p3;

assign zext_ln83_26_fu_1014_p1 = select_ln83_26_fu_1006_p3;

assign zext_ln83_27_fu_1036_p1 = select_ln83_27_fu_1028_p3;

assign zext_ln83_28_fu_1058_p1 = select_ln83_28_fu_1050_p3;

assign zext_ln83_29_fu_1080_p1 = select_ln83_29_fu_1072_p3;

assign zext_ln83_2_fu_486_p1 = select_ln83_2_fu_478_p3;

assign zext_ln83_30_fu_1102_p1 = select_ln83_30_fu_1094_p3;

assign zext_ln83_31_fu_1124_p1 = select_ln83_31_fu_1116_p3;

assign zext_ln83_32_fu_1146_p1 = select_ln83_32_fu_1138_p3;

assign zext_ln83_33_fu_1168_p1 = select_ln83_33_fu_1160_p3;

assign zext_ln83_34_fu_1190_p1 = select_ln83_34_fu_1182_p3;

assign zext_ln83_35_fu_1212_p1 = select_ln83_35_fu_1204_p3;

assign zext_ln83_36_fu_1234_p1 = select_ln83_36_fu_1226_p3;

assign zext_ln83_37_fu_1256_p1 = select_ln83_37_fu_1248_p3;

assign zext_ln83_38_fu_1278_p1 = select_ln83_38_fu_1270_p3;

assign zext_ln83_39_fu_1300_p1 = select_ln83_39_fu_1292_p3;

assign zext_ln83_3_fu_508_p1 = select_ln83_3_fu_500_p3;

assign zext_ln83_40_fu_1322_p1 = select_ln83_40_fu_1314_p3;

assign zext_ln83_41_fu_1344_p1 = select_ln83_41_fu_1336_p3;

assign zext_ln83_42_fu_1366_p1 = select_ln83_42_fu_1358_p3;

assign zext_ln83_43_fu_1388_p1 = select_ln83_43_fu_1380_p3;

assign zext_ln83_44_fu_1410_p1 = select_ln83_44_fu_1402_p3;

assign zext_ln83_45_fu_1432_p1 = select_ln83_45_fu_1424_p3;

assign zext_ln83_46_fu_1454_p1 = select_ln83_46_fu_1446_p3;

assign zext_ln83_47_fu_1476_p1 = select_ln83_47_fu_1468_p3;

assign zext_ln83_48_fu_1498_p1 = select_ln83_48_fu_1490_p3;

assign zext_ln83_49_fu_1520_p1 = select_ln83_49_fu_1512_p3;

assign zext_ln83_4_fu_530_p1 = select_ln83_4_fu_522_p3;

assign zext_ln83_5_fu_552_p1 = select_ln83_5_fu_544_p3;

assign zext_ln83_6_fu_574_p1 = select_ln83_6_fu_566_p3;

assign zext_ln83_7_fu_596_p1 = select_ln83_7_fu_588_p3;

assign zext_ln83_8_fu_618_p1 = select_ln83_8_fu_610_p3;

assign zext_ln83_9_fu_640_p1 = select_ln83_9_fu_632_p3;

assign zext_ln83_fu_442_p1 = select_ln83_fu_434_p3;

endmodule //relu_1
