KerasJson: /media/data/projects/landsat_soil_classifier/models/ANN100x100.json
KerasH5:   /media/data/projects/landsat_soil_classifier/models/ANN100x100_weights.h5
InputData: /media/data/projects/landsat_soil_classifier/data/Landsat_x_test.dat
OutputPredictions: /media/data/projects/landsat_soil_classifier/data/Landsat_y_test.dat
OutputDir: /media/data/projects/landsat_soil_classifier/fpga/hls_ANN100x100
ProjectName: fpga_ANN100x100
XilinxPart: xazu7eg-fbvb900-1-i
ClockPeriod: 24

IOType: io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<24,8>
    ReuseFactor: 16
    Strategy: Resource
