KerasJson: /media/data/projects/landsat_soil_classifier/models/ANN50x50.json
KerasH5:   /media/data/projects/landsat_soil_classifier/models/ANN50x50_weights.h5
InputData: /media/data/projects/landsat_soil_classifier/data/sat_x_test.dat
OutputPredictions: /media/data/projects/landsat_soil_classifier/data/sat_y_test.dat 
OutputDir: /media/data/projects/landsat_soil_classifier/fpga/hls_minimal
ProjectName: fpga_minimal
XilinxPart: xazu7eg-fbvb900-1-i
ClockPeriod: 24

IOType: io_parallel # options: io_serial/io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<24,8>
    ReuseFactor: 4
    # Strategy: Latency
    # Strategy: Resource
  # LayerType:
  #   Dense:
  #     ReuseFactor: 2
  #     Strategy: Resource
  #     Compression: True